encoding: utf-8
markdown: kramdown
title: Project Euler English mirror
description: "English mirror of Project Euler as a github.io site ready for translation"
baseurl: "/pe-id/"
permalink: "/:categories/:title.html"
